# 21.4 任务终结
- [一、装饰性花园](#一、装饰性花园)
- [二、在阻塞时终结](#二、在阻塞时终结)
- [三、中断](#三、中断)
- [四、检查中断](#四、检查中断)

在前面的某些例子中，cancel()和isCanceled()方法被放到一个所有任务都可以看到的类中。这些任务通过检查isCanceled()来确定何时终止它们自己，通常来说，这是一种合理的方式。
但是，在某些情况下，任务必须更加突然地终止。本节你将学习到有关这种终止的各类话题和问题。

首先，让我们观察一个示例，它不仅演示了终止问题，而且还是一个资源共享的示例。

---

## 一、装饰性花园
在这个仿真程序中，公园管理委员会希望了解每天通过多个大门进入公园的总人数。每个大门都有一个十字转门或某种其他形式的计数器，并且任何一个十字转门的计数值递增时，表示公园中总人数的共享计数值也会递增。
```java
package concurrency;
import java.util.concurrent.*;
import java.util.*;

class Count {
	private int count = 0;
	private Random rand = new Random(47);
	// Remove the synchronized keyword to see counting fail:
	public synchronized int increment() {
		int temp = count;
		if(rand.nextBoolean())  // Yield half the time
			Thread.yield();
		return (count = ++temp);
	}
	public synchronized int value() { return count; }
}

class Entrance implements Runnable {
	private static Count count = new Count();
	private static List<Entrance> entrances = 
			new ArrayList<Entrance>();
	private int number = 0;
	// Doesn't need synchronization to read:
	private final int id;
	private static volatile boolean canceled = false;
	// Atomic operation on a volatile field:
	public static void cancel() { canceled = true; }
	public Entrance(int id) {
		this.id = id;
		// Keep this task in a list. Also prevents
		// garbage collection of dead tasks:
		entrances.add(this);
	}
	public void run() {
		while(!canceled) {
			synchronized(this) {
				++number;
			}
			System.out.println(this + " Total: " + count.increment());
			try {
				TimeUnit.MILLISECONDS.sleep(100);
			} catch(InterruptedException e) {
				System.out.println("sleep interrupted");
			}
		}
		System.out.println("Stopping " + this);
	}
	public synchronized int getValue() { return number; }
	public String toString() {
		return "Entrance " + id + ": " + getValue();
	}
	public static int getTotalCount() {
		return count.value();
	}
	public static int sumEntrances() {
		int sum = 0;
		for(Entrance entrance : entrances)
			sum += entrance.getValue();
		return sum;
	}
}

public class OrnamentalGarden {
	public static void main(String[] args) throws Exception {
		ExecutorService exec = Executors.newCachedThreadPool();
		for(int i = 0; i < 5; i++)
			exec.execute(new Entrance(i));
		// Run for a while, then stop and collect the data:
		TimeUnit.SECONDS.sleep(3);
		Entrance.cancel();
		exec.shutdown();
		if(!exec.awaitTermination(250, TimeUnit.MILLISECONDS))
			System.out.println("Some tasks were not terminated!");
		System.out.println("Total: " + Entrance.getTotalCount());
		System.out.println("Sum of Entrances: " + Entrance.sumEntrances());
	}
}/*Output:
Entrance 0: 1 Total: 1
Entrance 4: 1 Total: 5
Entrance 1: 1 Total: 3
Entrance 2: 1 Total: 2
Entrance 3: 1 Total: 4
Entrance 3: 2 Total: 6
Entrance 0: 2 Total: 10
Entrance 4: 2 Total: 9
Entrance 2: 2 Total: 8
Entrance 1: 2 Total: 7
...
Entrance 4: 28 Total: 136
Entrance 3: 28 Total: 137
Entrance 1: 28 Total: 138
Entrance 0: 28 Total: 139
Entrance 2: 28 Total: 140
Entrance 3: 29 Total: 141
Entrance 4: 29 Total: 142
Entrance 1: 29 Total: 143
Entrance 0: 29 Total: 144
Entrance 2: 29 Total: 145
Entrance 3: 30 Total: 146
Entrance 4: 30 Total: 147
Entrance 1: 30 Total: 148
Entrance 0: 30 Total: 149
Entrance 2: 30 Total: 150
Stopping Entrance 3: 30
Stopping Entrance 4: 30
Stopping Entrance 1: 30
Stopping Entrance 2: 30
Stopping Entrance 0: 30
Total: 150
Sum of Entrances: 150
```
这里使用单个的Count对象来跟踪公园参观者的主计数值，并且将其当作Entrance类中的一个静态域进行存储。Count.increment()和Count.value()都是synchronized的，
用来控制对count域的访问。increment()方法使用了Random对象，目的是在从把count读取到temp中，到递增temp并将其存储回count的这段时间里，有大约一半的时间产生让步。
如果你将increment()上的synchronized关键字注释掉，那么这个程序就会崩溃，因为多个任务将同时访问并修改count（yield()会使问题更快地发生）。

每个Entrance任务都维护者一个本地值number，它包含通过某个特定入口进入的参观者的数量。这提供了对count对象的双重检查，以确保其记录的参观者数量是正确的。
Entrance.run()只是递增number和count对象，然后休眠100毫秒。

因为Entrance.canceled是一个volatile的布尔值，而它只会被读取和赋值（不会与其他域组合在一起被读取），所以不需要同步对其的访问，就可以安全地操作它。
如果你对诸如此类的情况有任何疑虑，那么最好总是使用synchronized。

这个程序在以稳定的方式关闭所有事物方面还有一些小麻烦，其部分原因是为了说明在终止多线程程序时你必须相当小心，而另一部分原因是为了演示interrupted()的值，
稍后你将学习有关这个值的知识。

在3秒钟之后，main()向Entrance发送static cancel()消息，然后调用exec对象的shutdown()方法，之后调用exec上的awaitTermination()方法。
ExecutorService.awaitTermination()等待每个任务结束，如果所有的任务在超时时间达到之前全部结束，则返回true，否则返回false，表示不是所有的任务都已经结束了。
尽管这会导致每个任务都退出其run()方法，并因此作为任务而终止，但是Entrance对象仍旧是有效的，因为在构造器中，每个Entrance对象都存储在称为entrances的静态List<Entrance>中。
因此，sunEntrances()仍旧可以作用于这些有效的Entrance对象。

当这个程序运行时，你将看到，在人们通过十字转门时，将显示总人数和通过每个入口的人数。如果移除Count.increment()上面的synchronized声明，你将会注意到总人数与你的期望有差异，
每个十字转门统计的人数将与count中的值不同。只要用互斥来同步对Count的访问，问题就可以解决了。请记住，Count.increment()通过使用temp和yield()，增加了失败的可能性。
在真正的线程问题中，失败的可能性从统计学角度看可能非常小，因此你可能很容易就掉进了轻信所有事物都将正确工作的陷阱里。就像在上面的示例中，有些还未发生的问题就有可能会隐藏起来，
因此复审并发代码时，要格外地仔细。

**练习17：（2）创建一个辐射计数器，它可以具有任何数量的传感器。**

**答案请戳:point_right:[这里](solutions/Ex17.md)**

## 二、在阻塞时终结
前面示例中的Entrance.run()在其循环中包含对sleep()的调用。我们知道，sleep()最终将被唤醒，而任务也将返回到循环开始部分，去检查conceled标志，从而决定是否跳出循环。
但是，调用sleep()会使任务从执行状态变为被阻塞状态，而有时你必须终止被阻塞的任务。

### 线程状态
一个线程可以处于以下四种状态之一：
1. **新建（new）**：当线程被创建时，它只会短暂地处于这种状态。此时它已经分配了必需的系统资源，并执行了初始化。此刻线程已经有资格获得CPU时间了，之后调度器将把这个线程转变为可运行状态或阻塞状态。
2. **就绪（Runnable）**：在这种状态下，只要调度器把时间片分配给了线程，线程就可以运行了。也就是说，处于此种状态的线程，随时都可以运行，只要调度器能分配时间片给它。这不同与死亡和阻塞状态。
3. **阻塞（Blocked）**：线程能够运行，但有某个条件阻止了它的运行。当线程处于阻塞状态时，调度器将忽略线程，不会分配给线程任何CPU时间。直到线程重新进入了就绪状态，它才有可能执行。
4. **死亡（Dead）**：处于死亡或终止状态的线程将不再是可调度的，并且再也不会得到CPU时间，它的任务已结束，或不再是可运行的了。任务的结束通常以run()方法返回为标志，但是驱动该任务的线程还可以被中断。

### 进入阻塞状态
一个任务进入阻塞装填，可能有如下原因：
1. 通过调用sleep(miliseconds)使任务进入休眠状态，在这种情况下，任务在指定的时间内不会运行。
2. 你通过调用wait()使线程挂起。直到线程得到了notify()或notifyAll()消息（或者在Java SE5的java.util.concurrent类库中等价的signal()或signalAll()消息），线程才会进入就绪状态。
3. 任务在等待某个输入/输出的完成。
4. 任务试图在某个对象上调用其同步控制方法，但是该对象的锁不可用，因为另一个任务已经获取了这个锁。

在较早的代码中，也可能会看到用suspend()和resume()在阻塞和唤醒线程，但是在现代Java中这些方法被废止了（因为可能导致死锁），所以本书不讨论这些内容。
stop()方法也已经被废止了，因为它不释放线程获得的锁，并且如果线程处于不一致状态（就是“受损状态”），其他任务可以在这种状态下浏览并修改它们。这样所产生的问题是微妙而难以被发现的。

现在我们需要查看的问题是：有时你希望能够终止处于阻塞状态的任务。如果对于处于阻塞状态的任务，你不能等待其到达代码中可以检查其状态值的某一点，因而决定让它主动地终止，那么你就必须强制这个任务跳出其阻塞状态。

## 三、中断
正如你所想象的，在Runnable.run()方法的中间打断它，与在该方法中判断cancel标志，或是程序员准备好离开该方法的其他方式相比，要棘手很多。当你打断被阻塞的任务时，可能需要清理资源。
正因为这一点，在任务的run()方法中间打断，更像是抛出了一个异常，因此在Java线程的这类中断中就用到了异常（这会滑向异常的不恰当用法，因为这意味着你会经常用它们来控制流程）。
为了能以这种方式终止任务并返回良好的状态，你必须仔细考虑代码的执行路径，并仔细编写catch子句以便正确清除所有事物。

Thread类包含interrupt()方法，因此你可以终止被阻塞的任务，这个方法将设置线程的中断状态。如果一个线程已经被阻塞，或者试图执行一个阻塞操作，那么设置这个线程的中断状态将抛出InterruptedException。
当抛出该异常或者该任务调用Thread.interrupted()时，中断状态将被复位。正如你将看到的，Thread.interrupted()提供了离开run()循环而不抛出异常的第二种方式。

为了调用interrupt()，你必须持有Thread对象。你可能已经注意到了，新的concurrent类库似乎在避免对Thread对象的直接操作，转而尽量通过Executor来执行所有操作。
如果你在Executor上调用shutdownNow()，那么它将发送一个interrupt()调用给它启动的所有线程。这么做是有意义的，因为当你完成工程中的某个部分或整个程序时，通常会希望同时关闭某个特定Executor的所有任务。
然而，你有时也会希望只中断某个单一任务。如果使用Executor，那么通过调用submit()而不是executor()来启动任务，就可以持有该任务的上下文。submit()将返回一个泛型Future<?>，
其中有一个未修饰的参数，因为你永远都不会在其上调用get()——持有这种Future的目的在于你可以在其上调用cancel()，并因此可以使用它来中断某个特定任务。
如果你将true传递给cancel()，那么它就会拥有在该线程上调用interrupt()以停止这个线程的权限。因此cancel()是一种中断由Executor启动的单个线程的方式。

下面的示例用Executor展示了基本的interrupted()用法：
```java
package concurrency;
import java.util.concurrent.*;
import java.io.*;

class SleepBlocked implements Runnable {
	public void run() {
		try {
			TimeUnit.SECONDS.sleep(100);
		} catch(InterruptedException e) {
			System.out.println("InterruptedException");
		}
		System.out.println("Exiting SleepBlocked.run()");
	}
}

class IOBlocked implements Runnable {
	private InputStream in;
	public IOBlocked(InputStream is) { in = is; }
	public void run() {
		try {
			System.out.println("Waiting for read():");
			in.read();
		} catch(IOException e) {
			if(Thread.currentThread().isInterrupted()) {
				System.out.println("Interrupted from blocked I/O");
			} else {
				throw new RuntimeException();
			}
		}
		System.out.println("Exiting IOBlocked.run()");
	}
}

class SynchronizedBlocked implements Runnable {
	public synchronized void f() {
		while(true)  // Never releases lock
			Thread.yield();
	}
	public SynchronizedBlocked() {
		new Thread() {
			public void run() {
				f();   // Lock acquired by this thread
			}
		}.start();
	}
	public void run() {
		System.out.println("Trying to call f()");
		f();
		System.out.println("Exiting SynchronizedBlocked.run()");
	}
}

public class Interrupting {
    private static ExecutorService exec = Executors.newCachedThreadPool();
    static void test(Runnable r) throws InterruptedException {
    	Future<?> f = exec.submit(r);
    	TimeUnit.MILLISECONDS.sleep(100);
    	System.out.println("Interrupting " + r.getClass().getName());
    	f.cancel(true);  // Interrupts if running
    	System.out.println("Interrupt sent to " + r.getClass().getName());
    }
	public static void main(String[] args) throws Exception {
        test(new SleepBlocked());
        test(new IOBlocked(System.in));
        test(new SynchronizedBlocked());
        TimeUnit.SECONDS.sleep(3);
        System.out.println("Aborting with System.exit(0)");
        System.exit(0);   // ... since last 2 interrupts failed
	}
}/*Output:
Interrupting concurrency.SleepBlocked
Interrupt sent to concurrency.SleepBlocked
InterruptedException
Exiting SleepBlocked.run()
Waiting for read():
Interrupting concurrency.IOBlocked
Interrupt sent to concurrency.IOBlocked
Trying to call f()
Interrupting concurrency.SynchronizedBlocked
Interrupt sent to concurrency.SynchronizedBlocked
Aborting with System.exit(0)
*///
```
上面的每个任务都表示一种不同类型的阻塞。SleepBlocked是可中断的阻塞示例，而IOBlocked和SynchronizedBlocked是不可中断的阻塞示例。这个程序证明I/O和在synchronized块上的等待是不可中断的，
但是通过浏览代码，你也可以预见到这一点——无论是I/O还是尝试调用synchronized方法，都不需要任务InterruptedException处理器。

前两个类很简单直观：在第一个类中run()方法调用了sleep()，而在第二个类中调用了read()。但是，为了演示SynchronizedBlocked，我们必须首先获取锁。这是通过在构造器中创建匿名的Thread类的示例来实现的，
这个匿名Thread类的对象通过调用f()获取了对象锁（这个线程必须有别于为SynchronizedBlocked驱动run()的线程，因为一个线程可以多次获得某个对象锁）。由于f()永远都不返回，
因此这个锁永远不会释放，而SynchronizedBlocked.run()在试图调用f()，并阻塞以等待这个锁被释放。

从输出中可以看到，你能够中断对sleep()的调用（或者任何要求抛出InterruptedException的调用）。但是，你不能中断正在试图获取synchronized锁或者试图执行I/O操作的线程。
这有点令人烦恼，特别是在创建执行I/O的任务时，因为这意味着I/O具有锁住你的多线程程序的潜在可能。特别是对基于Web的程序，这更是关乎利害。

对于这类问题，有一个略显笨拙但是有时确实行之有效的解决方案，即关闭任务在其上发生阻塞的底层资源：
```java
package concurrency;
import java.util.concurrent.*;
import java.io.*;
import java.net.*;

public class CloseResource {
	
	public static void main(String[] args) throws Exception {
		ExecutorService exec = Executors.newCachedThreadPool();
		ServerSocket server = new ServerSocket(8080);
		InputStream socketInput =
				new Socket("localhost",8080).getInputStream();
		exec.execute(new IOBlocked(socketInput));
		exec.execute(new IOBlocked(System.in));
		TimeUnit.MILLISECONDS.sleep(100);
        System.out.println("Shutting down all threads");
        exec.shutdownNow();
        TimeUnit.SECONDS.sleep(1);
        System.out.println("Closing " + socketInput.getClass().getName());
        socketInput.close();  // Release blocked thread
        TimeUnit.SECONDS.sleep(1);
        System.out.println("Closing " + System.in.getClass().getName());
        System.in.close();   // Release blocked thread
	}

} /*Output:
Waiting for read(): 
Waiting for read(): 
Shutting down all threads 
Closing java.net.SocketInputStream 
Interrupted from blocked I/O 
Exiting IOBlocked.run() 
Closing java.io.BufferedInputStream 
Exiting IOBlocked.run() 
*///:~
```
在shutdownNow()被调用之后以及在两个输入流上调用close()之前的延迟强调的是一旦底层自愿被关闭，任务将解除阻塞。请注意，有一点很有趣，interrupt()看起来发生在关闭Socket而不是关闭System.in的时刻。

幸运的是，在第18章中介绍的各种nio类提供了更人性化的I/O中断。被阻塞的nio通道会自动地响应中断：
```java
// Interrupting a blocked NIO channel.
package concurrency;
import java.net.*;
import java.nio.*;
import java.nio.channels.*;
import java.util.concurrent.*;
import java.io.*;

class NIOBlocked implements Runnable {
	private final SocketChannel sc;
	public NIOBlocked(SocketChannel sc) { this.sc = sc; }
	public void run () {
		try {
			System.out.println("Waiting for read() in " + this);
			sc.read(ByteBuffer.allocate(1));
		} catch(ClosedByInterruptException e) {
			System.out.println("ClosedByInterruptException");
		} catch(AsynchronousCloseException e) {
			System.out.println("AsynchronousCloseException");
		} catch(IOException e) {
			throw new RuntimeException(e);
		}
		System.out.println("Exiting NIOBlocked.run() " + this);
	}
}

public class NIOInterruption {
	public static void main(String[] args) throws Exception {
        ExecutorService exec = Executors.newCachedThreadPool();
        ServerSocket server = new ServerSocket(8080);
        InetSocketAddress isa = new InetSocketAddress("localhost", 8080);
        SocketChannel sc1 = SocketChannel.open(isa);
        SocketChannel sc2 = SocketChannel.open(isa);
        Future<?> f = exec.submit(new NIOBlocked(sc1));
        exec.execute(new NIOBlocked(sc2));
        exec.shutdown();
        TimeUnit.SECONDS.sleep(1);
        // Produce an interrupt via cancel:
        f.cancel(true);
        TimeUnit.SECONDS.sleep(1);
        // Release the block by closing the channel:
        sc2.close();
	}
} /*Output:
Waiting for read() in concurrency.NIOBlocked@70d192f2
Waiting for read() in concurrency.NIOBlocked@7aa3aa20
ClosedByInterruptException
Exiting NIOBlocked.run() concurrency.NIOBlocked@7aa3aa20
AsynchronousCloseException
Exiting NIOBlocked.run() concurrency.NIOBlocked@70d192f2
*///
```
如你所见，你还可以关闭底层资源以释放锁，尽管这种做法一般不是必需的。注意，使用execute()来启动两个任务，并调用e.shutdownNow()将可以很容易地终止所有事物，
而对于捕获上面示例中的Future，只有在将中断发送给一个线程，同时不发送给另一个线程时才是必需的。

**练习18：（2）创建一个非任务的类，它有一个方法，该方法使用较长的时间间隔来调用sleep()。创建一个任务，它将调用这个非任务类上的这个方法。**
**在main()中，启动该任务，然后调用interrupt()来终止它。请确保这个任务被安全地关闭。**

**答案请戳:point_right:[这里](solutions/Ex18.md)**

**练习19：（4）修改OrnamentalGarden.java，使其使用interrupt()。**

**答案请戳:point_right:[这里](solutions/Ex19.md)**

**练习20：（1）修改CachedThreadPool.java，使所有任务在结束前都将收到一个interrupt()。**

**答案请戳:point_right:[这里](solutions/Ex20.md)**

### 被互斥所阻塞
就像在Interrupting.java中看到的，如果你尝试着在一个对象上调用其synchronized方法，而这个对象的锁已经被其他任务获得，那么调用方法的这个任务将被挂起（阻塞），
直至这个锁可获得。下面的示例说明了同一个互斥可以被同一个任务多次获得：
```java
// One thread can reacquire the same lock.
package concurrency;

public class MultiLock {
    public synchronized void f1(int count) {
    	if(count-- > 0) {
    		System.out.println("f1() calling f2() with count " + count);
    		f2(count);
    	}
    }
    public synchronized void f2(int count) {
    	if(count-- > 0) {
    		System.out.println("f2() calling f1() with count " + count);
    		f1(count);
    	}
    }
	public static void main(String[] args) {
        final MultiLock multiLock = new MultiLock();
        new Thread() {
        	public void run() {
        		multiLock.f1(10);
        	}
        }.start();
	}
} /*Output:
f1() calling f2() with count 9
f2() calling f1() with count 8
f1() calling f2() with count 7
f2() calling f1() with count 6
f1() calling f2() with count 5
f2() calling f1() with count 4
f1() calling f2() with count 3
f2() calling f1() with count 2
f1() calling f2() with count 1
f2() calling f1() with count 0
*///
```
在main()中创建了一个调用f1()的Thread，然后启动这个线程让f1()和f2()互相调用直至count变为0。由于这个任务已经在第一次对f1()的调用中获得了multiLock对象的锁，
因此该任务将在对f2()的调用中再次获得这个锁，以此类推。这么做是有意义的，即一个任务能够调用在同一个对象中的其他synchronized方法，因为这个任务已经持有锁了。

就像前面在不可中断的I/O中所观察到的那样，无论在任何时刻，只要任务以不可中断的方式被阻塞，那么都有可能会锁住程序。Java SE5并发类库中添加了一个特性，
即在ReentrantLock上阻塞的任务具备可以被中断的能力，这与在synchronized方法或临界区上阻塞的任务完全不同：
```java
// 中断使用ReentrantLock阻塞的任务。
package concurrency;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.*;

class BlockedMutex {
	private Lock lock = new ReentrantLock();
	public BlockedMutex() {
		// 立即获取它(锁住)，以演示在ReentrantLock上阻塞的任务的中断
		lock.lock();
	}
	public void f() {
		try {
			// 这将永远无法用于第二个任务
			lock.lockInterruptibly();  // 特殊的调用
			System.out.println("lock acquired in f()");
		} catch(InterruptedException e) {
			System.out.println("Interrupted from lock acquisition in f()");
		}
	}
}

class Blocked2 implements Runnable {
	BlockedMutex blocked = new BlockedMutex();
	public void run() {
		System.out.println("Waiting for f() in BlockedMutex");
		blocked.f();
		System.out.println("Broken out of blocked call");
	}
}

public class Interruptint2 {

	public static void main(String[] args) throws Exception {
        Thread t = new Thread(new Blocked2());
        t.start();
        TimeUnit.SECONDS.sleep(1);
        System.out.println("Issuing t.interrupt()");
        t.interrupt();
	}

} /*Output:
Waiting for f() in BlockedMutex
Issuing t.interrupt()
Interrupted from lock acquisition in f()
Broken out of blocked call
*///
```
BlockedMutex类在其构造器中会获取自身的Lock对象，也就是说BlockedMutex类会在构造器中将自己锁住，并且不再释放这个锁。
因此，如果你试图从第二个任务（自定义的线程Blocked2）中调用f()，会因为无法获得BlockedMutex对象的锁而被阻塞。
所以，在Blocked2类中，run()方法总是在调用blocked.f()的地方停止。但是当运行程序时，与I/O调用不同，interrupt()可以中断这个被阻塞的任务，
因为它该阻塞是发生在ReentrantLock上的。

## 四、检查中断
注意，当你在线程上调用interrupt()时，中断是发生在任务要进入到阻塞操作中，或者已经在阻塞操作内部了。如果你只能通过在阻塞调用上抛出异常来退出，那么你就无法正常的结束run()循环。
因此，当你调用interrupt()以停止某个任务，并且在run()循环中碰巧没有产生任何阻塞调用时，你需要用另一种方式来退出。

这种方式是由中断状态来表示的，其状态可以通过调用interrupt()来设置。你可以通过调用interrupted()来检查中断的状态，它不仅可以让你知道interrupt()是否被调用过，而且还可以清除中断状态。
清除中断状态可以确保并发结构不会就某个任务被中断而通知你两次，你可以通过单一的InterruptedException异常或调用Thread.interrupted()来得到这种通知。
如果想再次检查中断状态，则可以在调用Thread.interrupted()时将结果存储起来。

下面的示例展示了典型的惯用法，你应该在run()方法中用它来处理中断状态被设置时，被阻塞和不被阻塞的各种可能：
```java
// 中断任务的惯用法。
// {Args: 1100}
package concurrency;

import java.util.concurrent.TimeUnit;

class NeedsCleanup {
	private final int id;
	public NeedsCleanup(int ident) {
		id = ident;
		System.out.println("NeedsCleanup " + id);
	}
	public void cleanup() {
		System.out.println("Cleaning up " + id);
	}
}

class Blocked3 implements Runnable {
	private volatile double d = 0.0;
	public void run() {
		try {
			while(!Thread.interrupted()) {  // 判断任务中断状态
				// point1
				NeedsCleanup n1 = new NeedsCleanup(1);
				// 定义n1之后立刻开始try-finally， 以保证n1被正确的清除
				try {
					System.out.println("Sleeping");
					TimeUnit.SECONDS.sleep(1);
					// point2
					NeedsCleanup n2 = new NeedsCleanup(2);
					// 保证正确的清除n2
					try {
						System.out.println("Calculating");
						// 一个费时的非阻塞操作：
						for(int i = 1; i < 2500000; i++)
							d = d + (Math.PI + Math.E) / d;
						System.out.println("Finished time-consuming operation");
					} finally {
						n2.cleanup();
					}
				} finally {
					n1.cleanup();
				}
			}
			System.out.println("Exiting via while() test");
		} catch(InterruptedException e) {
			System.out.println("Exiting via InterruptedException");
		}
	}
}

public class InterruptingIdiom {

	public static void main(String[] args) throws Exception {
        if(args.length != 1) {
        	System.out.println("usage: java InterruptingIdiom delay-in-mS");
        	System.exit(1);
        }
        Thread t = new Thread(new Blocked3());
        t.start();
        TimeUnit.MILLISECONDS.sleep(new Integer(args[0]));
        t.interrupt();
	}

}/*Output:
NeedsCleanup 1
Sleeping
NeedsCleanup 2
Calculating
Finished time-consuming operation
Cleaning up 2
Cleaning up 1
NeedsCleanup 1
Sleeping
Cleaning up 1
Exiting via InterruptedException
*///
```
NeedsCleanup类强调在你经由异常离开循环时，正确清理资源的必要性。注意，所有在Blocked3.run()中创建的NeedsCleanup资源都必须在其后紧跟try-finally子句，以确保cleanup()方法总是被调用。

我们通过一个命令行参数，来表示在调用interrupt()之前以毫秒为单位的延迟时间。通过使用不同的延迟时间，可以使程序从两处不同位置退出Blocked3.run()：
一处在阻塞的sleep()调用中，另一处在非阻塞的数学计算中（在我的电脑中，当延迟时间为2100毫秒时会出现这种情况）。当程序从非阻塞的数学计算中退出时（即对interrupe()的调用发生在注释point2之后），
则所有的本地资源将被销毁，最后while循环会以正常方式从顶部退出。但是，如果interrupt()的调用发生在注释point1与point2之间（即在阻塞操作sleep()之前或其过程中），
那么该任务就会经由InterruptedException异常而退出。在这种情况下，在异常被抛出之时被创建出来的NeedsCleanup对象也将被清除（在finally子句中调用cleanup()方法），
并且你还可以在捕获异常的catch子句中执行其他的清理工作。

被设计用来响应interrupt()的类必须建立一种策略，以确保维持其状态的一致性。这通常意味着所有需要清理的对象创建操作后面都必须紧跟一个try-finally子句，从而使得无论run()循环如何退出，
清理总会被执行。像这样的代码会工作的很好，但是，哎... 由于在Java中缺乏自动的析构器调用，因此这将依赖于客户端程序员去编写正确的try-finally子句。

---

### [上一节：共享受限资源](21.3_Resolving_shared_resource_contention.md)　　　　　　　　[下一节：线程之间的协作](21.5_Cooperation_between_tasks.md)






